# Generated by Django 5.0.4 on 2024-04-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetravel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.carbouser'),
        ),
    ]
