# Generated by Django 5.0.4 on 2024-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_carbouser_crypto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbouser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='basetravel',
            name='emission_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='stationprofile',
            name='type',
            field=models.CharField(choices=[('Metro', 'Metro'), ('Bus', 'Bus'), ('Train', 'Train')], max_length=255),
        ),
    ]
