# Generated by Django 5.0.4 on 2024-04-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_carbouser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictravel',
            name='basetravel_ptr',
        ),
        migrations.RemoveField(
            model_name='privatetravel',
            name='basetravel_ptr',
        ),
        migrations.RemoveField(
            model_name='publictravel',
            name='end_stop',
        ),
        migrations.RemoveField(
            model_name='publictravel',
            name='start_stop',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stationprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stationprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stationqrcode',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='tokens_accumulated',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_created=True)),
                ('type', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=8, default=0, max_digits=9)),
                ('end_time', models.DateTimeField(null=True)),
                ('in_progress', models.BooleanField(default=True)),
                ('emission_saved', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('end_stop', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_stop', to='authentication.stationprofile')),
                ('start_stop', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_stop', to='authentication.stationprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.carbouser')),
            ],
        ),
        migrations.DeleteModel(
            name='BaseTravel',
        ),
        migrations.DeleteModel(
            name='PrivateTravel',
        ),
        migrations.DeleteModel(
            name='PublicTravel',
        ),
    ]
