# Generated by Django 5.0.4 on 2024-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_stationprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=19),
        ),
    ]
