# Generated by Django 5.0.4 on 2024-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_journey_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='emission_saved',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
